language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python-psycopg2 python-lxml
install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - python setup.py test
  - flake8 .
notifications:
  email:
  - ci-notify@openlabs.co.in
