language: python
python:
  - 2.7
before_install:
  - sudo apt-get install python-lxml
install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - python setup.py test
  - python setup.py test_on_postgres
  - flake8 .
notifications:
  email:
  - ci-notify@openlabs.co.in
